# Generated by Django 5.1.1 on 2025-01-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=10)),
                ("total_quantity", models.PositiveIntegerField()),
                ("reserved_quantity", models.PositiveIntegerField()),
                ("min_stock_level", models.PositiveIntegerField(default=10)),
                ("max_stock_level", models.PositiveIntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "In Stock"),
                            ("LOW_STOCK", "Low Stock"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                        ],
                        default="IN_STOCK",
                        max_length=20,
                    ),
                ),
                (
                    "unit_location",
                    models.CharField(
                        choices=[
                            ("AISLE", "Aisle"),
                            ("RACK", "Rack"),
                            ("SHELF", "Shelf"),
                        ],
                        default="SHELF",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=10)),
                ("quantity_change", models.PositiveIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Restock"),
                            ("SALE", "Sale"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                            ("DAMAGED", "Damaged Goods"),
                        ],
                        default="SALE",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(null=True)),
                (
                    "inventory_entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryentry",
                    ),
                ),
            ],
        ),
    ]
