# Generated by Django 5.1.1 on 2025-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=10)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
