# Generated by Django 5.1.1 on 2025-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="total",
            field=models.FloatField(default="", max_length=5),
        ),
    ]
