# Generated by Django 5.1.1 on 2025-01-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderitem_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="total",
            field=models.IntegerField(),
        ),
    ]
