# Generated by Django 5.1.1 on 2025-02-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOW_STOCK", "Low Stock"),
                            ("ORDER_STATUS", "Order Status"),
                            ("DELIVERY_UPDATE", "Delivery Update"),
                        ],
                        default="ORDER_STATUS",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=150)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("content", models.CharField(max_length=200)),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("SERIOUS", "Serious"),
                            ("MILD", "Mild"),
                            ("NORMAL", "Normal"),
                        ],
                        default="NORMAL",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="SENT",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "Sms")],
                        default="EMAIL",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
